# Generated by Django 5.2.4 on 2025-08-08 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsetting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOfferQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('daily_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='systemsetting.dailyoffer')),
            ],
        ),
        migrations.CreateModel(
            name='DailyOfferAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='systemsetting.dailyofferquestion')),
            ],
        ),
    ]
