# Generated by Django 5.2.4 on 2025-11-08 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsetting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOfferQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=500, null=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('daily_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='systemsetting.dailyoffer')),
            ],
        ),
        migrations.CreateModel(
            name='DailyOfferAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, max_length=300, null=True)),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='answers/')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='systemsetting.dailyofferquestion')),
            ],
        ),
        migrations.CreateModel(
            name='DailyOfferAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('half_day', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reward_given', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemsetting.dailyoffer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'offer', 'assigned_date', 'half_day'), name='unique_offer_per_user_per_day_half')],
            },
        ),
    ]
