# Generated by Django 5.2.4 on 2025-08-14 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemsetting', '0002_dailyofferquestion_dailyofferanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyofferanswer',
            name='is_correct',
        ),
    ]
