# Generated by Django 5.2.4 on 2025-08-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsetting', '0004_dailyofferassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyofferassignment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyofferassignment',
            name='half_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyofferassignment',
            name='assigned_date',
            field=models.DateField(),
        ),
    ]
