# Generated by Django 5.2.4 on 2025-08-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsetting', '0005_dailyofferassignment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyofferassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyofferassignment',
            name='reward_given',
            field=models.BooleanField(default=False),
        ),
    ]
