# Generated by Django 5.2.4 on 2025-08-19 05:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsetting', '0006_dailyofferassignment_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyofferassignment',
            constraint=models.UniqueConstraint(fields=('user', 'offer', 'assigned_date'), name='unique_offer_per_user_per_day'),
        ),
    ]
