# Generated by Django 5.2.4 on 2025-08-19 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsetting', '0007_dailyofferassignment_unique_offer_per_user_per_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyofferassignment',
            name='unique_offer_per_user_per_day',
        ),
        migrations.AddConstraint(
            model_name='dailyofferassignment',
            constraint=models.UniqueConstraint(fields=('user', 'offer', 'assigned_date', 'half_day'), name='unique_offer_per_user_per_day_half'),
        ),
    ]
