# Generated by Django 5.2.4 on 2025-08-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsetting', '0008_remove_dailyofferassignment_unique_offer_per_user_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyofferanswer',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
        migrations.AddField(
            model_name='dailyofferanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyofferassignment',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyofferquestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='dailyofferanswer',
            name='answer_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dailyofferquestion',
            name='question_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
