# Generated by Django 5.2.4 on 2025-10-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsetting', '0009_dailyofferanswer_answer_image_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyofferassignment',
            name='unique_offer_per_user_per_day_half',
        ),
        migrations.RemoveField(
            model_name='dailyofferassignment',
            name='user',
        ),
        migrations.AddField(
            model_name='dailyofferassignment',
            name='visitor_id',
            field=models.CharField(db_index=True, default='default_visitor', max_length=64),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='dailyofferassignment',
            constraint=models.UniqueConstraint(fields=('visitor_id', 'offer', 'assigned_date', 'half_day'), name='unique_offer_per_visitor_per_day_half'),
        ),
    ]
