# Generated by Django 5.2.4 on 2025-10-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('visitor_id', 'question')},
        ),
        migrations.AddField(
            model_name='useranswer',
            name='visitor_id',
            field=models.CharField(db_index=True, default='guest', max_length=64),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
    ]
