# Generated by Django 5.2.4 on 2025-11-08

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='user',
            field=models.ForeignKey(
                default=1,  # temporary default user to satisfy existing rows
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='visitor_id',
        ),
    ]
