# Generated by Django 5.2.4 on 2025-11-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallettransaction_status_and_more'),
        ('wallet', '0002_user_fk'),
    ]

    operations = [
    ]
