# Generated by Django 5.2.4 on 2025-11-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_quiz_visitortask_delete_usertask_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
