# Generated by Django 5.2.4 on 2025-08-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
