# Generated by Django 5.2.4 on 2025-08-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_usertask_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='reward_given',
            field=models.BooleanField(default=False),
        ),
    ]
