# Generated by Django 5.2.4 on 2025-10-18 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_usertask_reward_given'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('assigned_date', models.DateField()),
                ('half_day', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reward_given', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
        migrations.AddConstraint(
            model_name='visitortask',
            constraint=models.UniqueConstraint(fields=('visitor_id', 'task', 'assigned_date', 'half_day'), name='unique_task_per_visitor_per_slot'),
        ),
    ]
